### PR TITLE
[MI-3198] Added the logic to check attachment size and attachment count when receiving attachments from MS Teams

### PR DESCRIPTION
**Pull request by manojmalik20**
#### Summary
Modified the unit tests a little bit

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/178

### CODE REVIEW

**Review by jespino — APPROVED** [review]
LGTM

**Comment by esarafianou** [comment]
@jespino shouldn't we check Image resolution as well? Or would that still happen in the MM server? I'm referring to the 2nd paragraph under Attachment limits and sizes here: https://docs.mattermost.com/channels/share-files-in-messages.html#attachment-limits-and-sizes

**Review by ayusht2810 — APPROVED** [review]

**Comment by esarafianou** [comment]
@manojmalik20 is it possible to also include the following restrictions as the docs say?

> Image files can be a maximum size of 7680 pixels x 4320 pixels, with a maximum image resolution of 33 MP (mega pixels) or 8K resolution, and a maximum raw image file size of approximately 253 MB. System admins can customize the maximum image resolution size within the config.json file. See our [Configuration Settings](https://docs.mattermost.com/configure/configuration-settings.html#maximum-image-resolution) product documentation for details.

**Comment by jespino** [comment]
@esarafianou I see value in adding that restriction, what do you think about adding them in another PR? Merge this and iterate.

**Comment by esarafianou** [comment]
Yes agreed. We can merge that and create a new PR to tackle it. I'll create a new Jira issue too to make sure we properly track this.

**Review by esarafianou — APPROVED** [review]

**Pull request merged**
